var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        Hello, world! I am a CommentBox generated by React.
      </div>
    );
  }
});

React.render(
  <CommentBox />,
  document.getElementById('example')
);
